pretrained_model_name: "runwayml/stable-diffusion-v1-5"
paths:
  instance_images: ./instance_images
  class_images: ./class_images
prompts:
  instance: "a cc lamp"
  class: "a lamp"
hyperparams:
  prior_sampling:
    num_class_images: 50
    sample_batch_size: 1
  training:
    prior_loss_weight: 1.0